export const mainData = {
  code: 200,
  lang: "el",
  items: [
    {
      id: 651,
      name: "Η Ακαδημία",
      url: "/",
      weight: 55,
      side_menu: false,
      submenu: [
        {
          id: 659,
          name: "Ίδρυση",
          url: "",
          parent: 651,
          weight: 0,
          side_menu: false,
          submenu: [
            {
              id: 677,
              name: "Ιστορικό",
              url: "/academy/istoriko",
              parent: 659,
              weight: 0,
            },
            {
              id: 678,
              name: "Σκοπός",
              url: "/academy/skopos",
              parent: 659,
              weight: 1,
            },
            {
              id: 679,
              name: "Ακαδημαϊκοί από τη σύσταση της Ακαδημίας",
              url: "/academy/akadimaikoi-apo-ti-systasi-tis-akadimias",
              parent: 659,
              weight: 2,
            },
            {
              id: 881,
              name: "Τα μέλη της Ακαδημίας Αθηνών",
              url: "/academy/ta-meli-tis-akadimias-athinon-kata-arhaiotita",
              parent: 659,
              weight: 3,
            },
          ],
        },
        {
          id: 660,
          name: "Μέλη",
          url: "/academy/ta-meli-tis-akadimias-athinon",
          parent: 651,
          weight: 1,
          side_menu: false,
          submenu: [],
        },
        {
          id: 661,
          name: "Οργάνωση",
          url: "",
          parent: 651,
          weight: 3,
          side_menu: true,
          submenu: [
            {
              id: 697,
              name: "Αρχές",
              url: "/academy/arhes",
              parent: 661,
              weight: 0,
            },
            {
              id: 698,
              name: "Τάξεις",
              url: "/academy/taxeis",
              parent: 661,
              weight: 1,
            },
            {
              id: 699,
              name: "Ολομέλεια",
              url: "/academy/olomeleia",
              parent: 661,
              weight: 2,
            },
            {
              id: 700,
              name: "Συμβούλια - Επιτροπές",
              url: "/academy/symboylia-epitropes",
              parent: 661,
              weight: 3,
            },
          ],
        },
        {
          id: 662,
          name: "Διοίκηση - Υπηρεσίες",
          url: "/academy/dioikisi",
          parent: 651,
          weight: 4,
          side_menu: false,
          submenu: [],
        },
        {
          id: 663,
          name: "Κανονισμός",
          url: "/academy/kanonismos",
          parent: 651,
          weight: 5,
          side_menu: false,
          submenu: [],
        },
        {
          id: 664,
          name: "Ευεργέτες - Δωρητές - Αθλοθέτες",
          url: "",
          parent: 651,
          weight: 6,
          side_menu: false,
          submenu: [
            {
              id: 684,
              name: "Ευεργέτες",
              url: "/academy/eyergetes",
              parent: 664,
              weight: 0,
            },
            {
              id: 685,
              name: "Μεγάλοι Δωρητές",
              url: "/academy/megaloi-dorites",
              parent: 664,
              weight: 1,
            },
            {
              id: 686,
              name: "Δωρητές",
              url: "/academy/dorites",
              parent: 664,
              weight: 2,
            },
            {
              id: 687,
              name: "Αθλοθέτες",
              url: "/academy/athlothetes",
              parent: 664,
              weight: 3,
            },
          ],
        },
        {
          id: 665,
          name: "Εποπτευόμενα Ιδρύματα",
          url: "/academy/categories/665",
          parent: 651,
          weight: 7,
          side_menu: false,
          submenu: [],
        },
        {
          id: 666,
          name: "Διεθνές Ενώσεις",
          url: "/academy/categories/666",
          parent: 651,
          weight: 8,
          side_menu: false,
          submenu: [],
        },
        {
          id: 667,
          name: "Επιτροπή Ισότητας των Φύλων",
          url: "/academy/epitropi-isotitas-ton-fylon",
          parent: 651,
          weight: 9,
          side_menu: false,
          submenu: [],
        },
        {
          id: 680,
          name: "Μέγαρο",
          url: "",
          parent: 651,
          weight: 2,
          side_menu: true,
          submenu: [
            {
              id: 681,
              name: "Εισαγωγή",
              url: "/academy/eisagogi",
              parent: 680,
              weight: 0,
            },
            {
              id: 682,
              name: "Εξωτερικό",
              url: "/academy/exoteriko",
              parent: 680,
              weight: 1,
            },
            {
              id: 683,
              name: "Εσωτερικό",
              url: "/academy/esoteriko",
              parent: 680,
              weight: 2,
            },
          ],
        },
      ],
    },
    {
      id: 652,
      name: "Έρευνα",
      url: "",
      weight: 56,
      side_menu: false,
      submenu: [
        {
          id: 668,
          name: "Ερευνητικά Κέντρα",
          url: "",
          parent: 652,
          weight: 0,
          side_menu: false,
          submenu: [
            {
              id: 882,
              name: "Κέντρον Ερεύνης των Νεοελληνικών Διαλέκτων και Ιδιωμάτων - Ι.Λ.Ν.Ε.",
              url: "",
              parent: 668,
              weight: 0,
            },
          ],
        },
        {
          id: 669,
          name: "Ερευνητικά Γραφεία",
          url: "",
          parent: 652,
          weight: 1,
          side_menu: false,
          submenu: [],
        },
        {
          id: 670,
          name: "Ερευνητικά Προγράμματα",
          url: "",
          parent: 652,
          weight: 2,
          side_menu: false,
          submenu: [],
        },
        {
          id: 671,
          name: "Ερευνητικές Υποδομές",
          url: "",
          parent: 652,
          weight: 3,
          side_menu: false,
          submenu: [],
        },
        {
          id: 672,
          name: "Επιτροπή Ερευνών",
          url: "",
          parent: 652,
          weight: 4,
          side_menu: false,
          submenu: [],
        },
        {
          id: 673,
          name: "Επιστημονικό Συμβούλιο (Ε.Σ.Ε.Κ.Α.Α.)",
          url: "",
          parent: 652,
          weight: 5,
          side_menu: false,
          submenu: [],
        },
      ],
    },
    {
      id: 653,
      name: "Δημοσιεύματα",
      url: "/publications",
      weight: 57,
      side_menu: false,
      submenu: [
        {
          id: 674,
          name: "Έντυπα",
          url: "/publications",
          parent: 653,
          weight: 0,
          side_menu: true,
          submenu: [
            {
              id: 689,
              name: "Πρακτικά",
              url: "/publication/praktika",
              parent: 674,
              weight: 0,
            },
            {
              id: 690,
              name: "Μνημεία της Ελληνικής Ιστορίας",
              url: "/publication/mnimeia-tis-ellinikis-istorias",
              parent: 674,
              weight: 1,
            },
            {
              id: 691,
              name: "Ελληνική βιβλιοθήκη",
              url: "/publication/elliniki-bibliothiki",
              parent: 674,
              weight: 2,
            },
            {
              id: 692,
              name: "Διάφορες εκδόσεις",
              url: "/publication/diafores-ekdoseis",
              parent: 674,
              weight: 3,
            },
            {
              id: 693,
              name: "Δημοσιεύματα Κέντρων Ερευνών",
              url: "/publication/dimosieymata-kentron-ereynon",
              parent: 674,
              weight: 4,
            },
            {
              id: 694,
              name: "Εκδόσεις του Ιδρύματος Κώστα και Ελένης Ουράνη",
              url: "/publication/ekdoseis-toy-idrymatos-kosta-kai-elenis-oyrani",
              parent: 674,
              weight: 5,
            },
            {
              id: 695,
              name: "Εκδόσεις της Επιτροπής Ερευνών",
              url: "/publication/ekdoseis-tis-epitropis-ereynon",
              parent: 674,
              weight: 6,
            },
            {
              id: 696,
              name: "Εκδόσεις υπό την Αιγίδα της Διεθνούς Ενώσεως Κλασικής  Αρχαιολογίας και της Διεθνούς Ενώσεως Ακαδημιών",
              url: "/publication/ekdoseis-ypo-tin-aigida-tis-diethnoys-enoseos-klasikis-arhaiologias-kai-tis-diethnoys",
              parent: 674,
              weight: 7,
            },
          ],
        },
        {
          id: 675,
          name: "Ηλεκτρονικά",
          url: "/publication/ilektronika-dimosieymata",
          parent: 653,
          weight: 1,
          side_menu: false,
          submenu: [],
        },
        {
          id: 676,
          name: "Το Βιβλιοπωλείο της Ακαδημίας Αθηνών",
          url: "/publication/bibliopoleio-tis-akadimias-athinon",
          parent: 653,
          weight: 2,
          side_menu: false,
          submenu: [],
        },
      ],
    },
    {
      id: 654,
      name: "Βραβεία",
      url: "/awards",
      weight: 58,
      side_menu: false,
      submenu: [],
    },
    {
      id: 655,
      name: "Υποτροφίες",
      url: "/scholarships",
      weight: 59,
      side_menu: false,
      submenu: [],
    },
    {
      id: 656,
      name: "Βιβλιοθήκη",
      url: "",
      weight: 60,
      side_menu: true,
      submenu: [
        {
          id: 873,
          name: "Γενικές Πληροφορίες",
          url: "/libraries/categories/867",
          parent: 656,
          weight: 1,
          side_menu: false,
          submenu: [],
        },
        {
          id: 874,
          name: "Ξεναγήσεις",
          url: "/libraries/categories/872",
          parent: 656,
          weight: 3,
          side_menu: false,
          submenu: [],
        },
        {
          id: 875,
          name: "Νέες Προσκτήσεις",
          url: "/libraries/categories/871",
          parent: 656,
          weight: 2,
          side_menu: false,
          submenu: [],
        },
        {
          id: 876,
          name: "Ανακοινώσεις",
          url: "/libraries/categories/870",
          parent: 656,
          weight: 0,
          side_menu: false,
          submenu: [],
        },
        {
          id: 877,
          name: "Χρήσιμες Συνδέσεις",
          url: "/libraries/categories/869",
          parent: 656,
          weight: 5,
          side_menu: false,
          submenu: [],
        },
        {
          id: 878,
          name: "Συλλογές Υλικού",
          url: "/libraries/categories/868",
          parent: 656,
          weight: 4,
          side_menu: false,
          submenu: [],
        },
        {
          id: 879,
          name: "Επιπλέον Πληροφορίες",
          url: "/libraries/categories/880",
          parent: 656,
          weight: 6,
          side_menu: false,
          submenu: [],
        },
      ],
    },
    {
      id: 657,
      name: "Ανακοινώσεις",
      url: "/announcements",
      weight: 61,
      side_menu: true,
      submenu: [
        {
          id: 861,
          name: "Δελτία Τύπου",
          url: "/announcements/categories/855",
          parent: 657,
          weight: 0,
          side_menu: false,
          submenu: [],
        },
        {
          id: 862,
          name: "Συνεδρίες",
          url: "/announcements/categories/856",
          parent: 657,
          weight: 1,
          side_menu: false,
          submenu: [],
        },
        {
          id: 863,
          name: "Εκδηλώσεις",
          url: "/announcements/categories/857",
          parent: 657,
          weight: 2,
          side_menu: false,
          submenu: [],
        },
        {
          id: 864,
          name: "Προκηρύξεις",
          url: "/announcements/categories/858",
          parent: 657,
          weight: 3,
          side_menu: false,
          submenu: [],
        },
        {
          id: 865,
          name: "Δημοπρασίες",
          url: "/announcements/categories/859",
          parent: 657,
          weight: 4,
          side_menu: false,
          submenu: [],
        },
        {
          id: 866,
          name: "Ανακοινώσεις Υποτροφιών",
          url: "/announcements/categories/860",
          parent: 657,
          weight: 5,
          side_menu: false,
          submenu: [],
        },
      ],
    },
    {
      id: 658,
      name: "Ψηφιακή Ακαδημία",
      url: "http://repository.academyofathens.gr",
      weight: 62,
      side_menu: false,
      submenu: [],
    },
  ],
};

export const pageContent = {
  footer: {
    contact: {
      title: "ΕΠΙΚΟΙΝΟΝΙΑ",
      address: "Πανεπιστημίου 28, 106 79 Αθήνα",
      phone: "Τ: 210 3634700",
      fax: "F: 210 3634806",
      email: "info@academyofathens.gr",
    },
    info: {
      title: "ΧΡΗΣΙΜΕΣ ΠΛΗΡΟΦΟΡΙΕΣ",
      list: [
        {
          title: "Ευρετήριο Προσώπων",
          url: "/",
        },
        {
          title: "Πρόσβαση",
          url: "/",
        },
        {
          title: "Δικαιώματα",
          url: "/",
        },
        {
          title: "Δελτία Τύπου",
          url: "/",
        },
        {
          title: "Προκηρύξεις",
          url: "/",
        },
      ]
    },
    reserved: "© 2023 Dotsoft. All Rights Reserved.",
  }
};
